### ISSUE TITLE
一直卡在port scan这里

### ISSUE THREAD

**Issue by ricohrh** [hktalent/scan4all#116]
go version go1.19.1 linux/amd64
Starting Nmap 7.93 ( https://nmap.org ) at 2022-09-23 15:08 UTC

我从fofa采集了一些ip  域名 
然后用 scan4all -l host.txt 一直卡住![image](https://user-images.githubusercontent.com/103866925/191993490-8b0c2432-0fef-4f32-b076-0b48f25a4fd8.png)

**Comment by hktalent** [comment]
-v
看看
