### ISSUE TITLE
fatal error: pcap.h: No such file or directory

### ISSUE THREAD

**Issue by Unkn0wnGh0st** [hktalent/scan4all#117]
# github.com/google/gopacket/pcap
/root/go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by hktalent** [comment]
- 1-use vendor for build
- 2、more see：
https://github.com/hktalent/scan4all/blob/main/.github/workflows/build.yml
* build-mac: brew install libpcap
* ubuntu-latest： sudo apt install -yy libpcap-dev upx gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
*
