### ISSUE TITLE
OUTPUT feature does not work at all.

### ISSUE THREAD

**Issue by secfb** [hktalent/scan4all#121]
Hello, first of all you have made a really good tool.
I'm starting a simple scan on the application and I want to view the results in a file. But this feature never really works.

When I use it as below, it doesn't save anything in the result.txt file.
`scan4all -l httpx.txt -v -o result.txt`

```PowerShell
OUTPUT:
   -o, -output string  file to write output to (optional)
   -json               write output in JSON lines format
   -csv                write output in csv format
```

I am using the following command to display the results. Sometimes this command doesn't quite work.

```
scan4all -l httpx.txt -v |tee scan4all.txt
```

**Comment by hktalent** [comment]
It is recommended to build an es server to receive it. It is too busy at present. This repair will take some time, or come back and try our pro version for you.

**Comment by secfb** [comment]
It is recommended to build an es server to receive it. =>How exactly does this happen? Can you provide some information?

**Comment by hktalent** [comment]
download and use latest
https://github.com/hktalent/scan4all/releases

**Comment by secfb** [comment]
Thank you for the answer. It's like it's not working. I am using the tee command.
