### ISSUE TITLE
Checksum in scan4all-*-checksums.txt for 2.8.5 is incorrect

### ISSUE THREAD

**Issue by suzuki-shunsuke** [hktalent/scan4all#122]
Thank you for your great project!

I found the checksum in [scan4all-linux-checksums.txt](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all-linux-checksums.txt) is incorrect.

```
cdc1088016c0b15519710de186bd8d57f8de693049e9279f45c6f5d5993a1396  scan4all_2.8.5_linux_amd64.zip
```

[scan4all_2.8.5_linux_amd64.zip](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all_2.8.5_linux_amd64.zip)

```console
$ sha256sum scan4all_2.8.5_linux_amd64.zip 
b34508789f73990ff11989c3bede26a47114c9d5b8f8de12fbf73a7c7ecc1daa  scan4all_2.8.5_linux_amd64.zip
```

The checksum in [scan4all-linux-checksums.txt](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all-linux-checksums.txt) is different from the checksum of [scan4all_2.8.5_linux_amd64.zip](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all_2.8.5_linux_amd64.zip).

Expected content of [scan4all-linux-checksums.txt](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all-linux-checksums.txt) is

```
b34508789f73990ff11989c3bede26a47114c9d5b8f8de12fbf73a7c7ecc1daa  scan4all_2.8.5_linux_amd64.zip
```

**Comment by suzuki-shunsuke** [comment]
Not only [scan4all-linux-checksums.txt](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all-linux-checksums.txt), but also [scan4all-mac-checksums.txt](https://github.com/hktalent/scan4all/releases/download/2.8.5/scan4all-mac-checksums.txt) is incorrect.


```console
$ sha256sum scan4all_2.8.5_macOS_amd64.zip scan4all_2.8.5_macOS_arm64.zip 
ccd874a283defad6a0deb11377cb9d6024cb5946b46f61f36008e0afe9db4950  scan4all_2.8.5_macOS_amd64.zip
73028ba0042fa0fdc59b535bff50ffbf003f9f086bf41e0112869ed7903f375c  scan4all_2.8.5_macOS_arm64.zip

$ cat scan4all-mac-checksums.txt 
2c5baf458432810098fd6c41c9ee64be9627051a5769c078d142b32e10e96959  scan4all_2.8.5_macOS_amd64.zip
76c08a33bf6a3fee51f83bd72d7416a6afb15f4676a2341ad3bd4fa05aedfe92  scan4all_2.8.5_macOS_arm64.zip
```

**Comment by hktalent** [comment]
Thanks, the hash check has been updated now
grateful
