### ISSUE TITLE
nmap 自动退出

### ISSUE THREAD

**Issue by linuxdy** [hktalent/scan4all#130]
SEE THE MAN PAGE (http://nmap.org/book/man.html) FOR MORE OPTIONS AND EXAMPLES
[ERR] Could not run nmap command: exit status 255
[FTL] Could not run enumeration: Could not run nmap command: exit status 255
![image](https://user-images.githubusercontent.com/50064309/208832370-8315bb97-d896-4b61-adf8-cc3e9db26b68.png)

**Comment by hktalent** [comment]
你可以外部nmap，直接使用结果文件xml

./scan4all -l nmapScanResults.xml  -v
