### ISSUE TITLE
execute "go build" command got error please advice how to fix thanks

### ISSUE THREAD

**Issue by odinchang2022** [hktalent/scan4all#134]
main.go:4:2: cannot find package "embed" in any of:
	/usr/lib/go-1.10/src/embed (from $GOROOT)
	/root/go/src/embed (from $GOPATH)
main.go:6:2: cannot find package "github.com/hktalent/scan4all/lib/api" in any of:
	/usr/lib/go-1.10/src/github.com/hktalent/scan4all/lib/api (from $GOROOT)
	/root/go/src/github.com/hktalent/scan4all/lib/api (from $GOPATH)
main.go:7:2: cannot find package "github.com/hktalent/scan4all/lib/util" in any of:
	/usr/lib/go-1.10/src/github.com/hktalent/scan4all/lib/util (from $GOROOT)
	/root/go/src/github.com/hktalent/scan4all/lib/util (from $GOPATH)

**Comment by hktalent** [comment]
go ver >=1.18
