### ISSUE TITLE
pattern config/*:

### ISSUE THREAD

**Issue by sec13b** [hktalent/scan4all#136]
┌──(root㉿Sec5)-[~/scan4all]
└─# go build                                          
main.go:14:12: pattern config/*: cannot embed directory config/nuclei-templates: contains no embeddable files
                                                                                                                                          
┌──(root㉿Sec5)-[~/scan4all]

**Comment by hktalent** [comment]
1-use git action for build
2-Or download release directly
https://github.com/hktalent/scan4all/releases
