### ISSUE TITLE
运行就卡住不动

### ISSUE THREAD

**Issue by safe6Sec** [hktalent/scan4all#14]
![image](https://user-images.githubusercontent.com/26316334/178106955-6f3cbd3c-c3d3-4a1f-98c9-089b23eeac2a.png)

**Comment by safe6Sec** [comment]
cpu，内存都没动静

**Comment by hktalent** [comment]
> cpu，内存都没动静

@safe6Sec 最新版本吗？建议用-v -debug看看到了哪一步
另外确认是好用最新版本？

**Comment by hktalent** [comment]
新加参数，允许在config.json控制，或命令方控制、取消优先使用nmap，然后就可以看到端口扫描的进度，避免以为程序卡死，
$ priorityNmap=false ./05-scan4all -l test.txt -stats=true

**Comment by safe6Sec** [comment]
> 新加参数，允许在config.json控制，或命令方控制、取消优先使用nmap，然后就可以看到端口扫描的进度，避免以为程序卡死， $ priorityNmap=false ./05-scan4all -l test.txt -stats=true

![image](https://user-images.githubusercontent.com/26316334/178135409-18abd5c1-4ac0-4190-89b4-2055b9365aca.png)
看起来是个新bug

**Comment by safe6Sec** [comment]
这个状态是什么报错，我环境是已经装了nmap。
![image](https://user-images.githubusercontent.com/26316334/178135512-879fb6ff-a34b-42cb-aac1-7c7378658b50.png)

**Comment by hktalent** [comment]
@safe6Sec 下载最新版本吧

**Comment by hktalent** [comment]
> 这个状态是什么报错，我环境是已经装了nmap。
> ![image](https://user-images.githubusercontent.com/26316334/178135512-879fb6ff-a34b-42cb-aac1-7c7378658b50.png)
@safe6Sec 下载最新版本吧
你的问题看上去是nmap运行失败了
你可以看看config/doNmapScan.sh
需要将root密码设置到PPSSWWDD
这样才可以正常运行nmap，或者建议你关闭nmap功能，使用慢速的naabu，并打开进度条：-stats=true

**Comment by safe6Sec** [comment]
> > 这个状态是什么报错，我环境是已经装了nmap。
> > ![image](https://user-images.githubusercontent.com/26316334/178135512-879fb6ff-a34b-42cb-aac1-7c7378658b50.png)
> > @safe6Sec 下载最新版本吧
> > 你的问题看上去是nmap运行失败了
> > 你可以看看config/doNmapScan.sh
> > 需要将root密码设置到PPSSWWDD
> > 这样才可以正常运行nmap，或者建议你关闭nmap功能，使用慢速的naabu，并打开进度条：-stats=true

我排查了一下，是--unique参数的问题。

**Comment by safe6Sec** [comment]
> > 新加参数，允许在config.json控制，或命令方控制、取消优先使用nmap，然后就可以看到端口扫描的进度，避免以为程序卡死， $ priorityNmap=false ./05-scan4all -l test.txt -stats=true
> 
> ![image](https://user-images.githubusercontent.com/26316334/178135409-18abd5c1-4ac0-4190-89b4-2055b9365aca.png) 看起来是个新bug

域名转ip有问题，建议接入dnsx

**Comment by hktalent** [comment]
@safe6Sec 把你的数据发来我测试下来，留下微信号吧，方便交流

**Comment by safe6Sec** [comment]
> @safe6Sec 把你的数据发来我测试下来，留下微信号吧，方便交流

微信号safe6sec-

**Comment by hktalent** [comment]
@safe6Sec 我这里并没有问题，三种形态的输入数据：ip 域名 url都容错了的，并没有错误呢
你确定是最新版本？
建议你删除当前目录中的config目录，程序会自动重新释放程序中最新的配置文件
<img width="195" alt="image" src="https://user-images.githubusercontent.com/18223385/178181595-d21c01a0-5748-4df5-ac8f-caf73a1bfd2d.png">

<img width="709" alt="image" src="https://user-images.githubusercontent.com/18223385/178181619-25ef0a43-17e4-49a5-a3a4-f413d0edcc7e.png">
