### ISSUE TITLE
不知道如何使用

### ISSUE THREAD

**Issue by hfw99** [hktalent/scan4all#20]
C:\Users\feng>go install github.com/hktalent/scan4all@2.4.8
go: github.com/hktalent/scan4all@2.4.8: github.com/hktalent/scan4all@2.4.8: invalid version: Get "https://proxy.golang.org/github.com/hktalent/scan4all/@v/2.4.8.info": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by hktalent** [comment]
@hfw99 
download from here:
https://github.com/hktalent/scan4all/releases

windows use:
https://github.com/hktalent/scan4all/releases/download/2.5.8/scan4all_2.5.8_windows_amd64.zip

scan4all.exe -host http://yoursite.com

**Comment by hfw99** [comment]
运行闪退



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 下午4:16
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hktalent/scan4all] 不知道如何使用 (Issue #20)





 
@hfw99
 download from here:
 https://github.com/hktalent/scan4all/releases
 
windows use:
 https://github.com/hktalent/scan4all/releases/download/2.5.8/scan4all_2.5.8_windows_amd64.zip
 
scan4all.exe -host http://yoursite.com

**Comment by hktalent** [comment]
@hfw99 
I need more details to help you
1. What operating system
2. How do you use it
3. Screenshots

**Comment by hktalent** [comment]
> 我需要怎么做才能跑起来
> […](#)

@hfw99

./scan4all.exe -l list.txt
./scan4all.exe -host yourSite.com

**Comment by hfw99** [comment]
是不是还要配置哪些环境



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 下午4:54
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hktalent/scan4all] 不知道如何使用 (Issue #20)





  
我需要怎么做才能跑起来
 …
  
@hfw99
 
./scan4all.exe -l list.txt
 ./scan4all.exe -host yourSite.com

**Comment by hktalent** [comment]
@hfw99
我这里win10
```
./scan4all.exe -host www.xaidu.com -v -debug
```
是没有问题的
如果你之前运行过，当前目录会产生config目录，可能存在兼容性问题，你删除当前目录中的config，重新运行即可

**Comment by hfw99** [comment]
删除了config目录再运行就行了，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hktalent/scan4all] 不知道如何使用 (Issue #20)





 
@hfw99
 我这里win10
 ./scan4all.exe -host www.xaidu.com -v -debug  
是没有问题的
 如果你之前运行过，当前目录会产生config目录，可能存在兼容性问题，你删除当前目录中的config，重新运行即可

**Comment by hktalent** [comment]
@hfw99 你开心、快乐，我就快乐
你好我好大家好
哈哈哈

**Comment by hfw99** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 晚上6:12
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hktalent/scan4all] 不知道如何使用 (Issue #20)





 
@hfw99 你开心、快乐，我就快乐
 你好我好大家好
 哈哈哈
