### ISSUE TITLE
-list test.txt 时候程序异常

### ISSUE THREAD

**Issue by SkyBlueEternal** [hktalent/scan4all#21]
>scan4all -list test.txt
badger 2022/07/20 23:35:45 INFO: All 0 tables opened in 0s
badger 2022/07/20 23:35:45 INFO: Replaying file id: 0 at offset: 0
badger 2022/07/20 23:35:45 INFO: Replay took: 14.894µs
badger 2022/07/20 23:35:45 DEBUG: Value log discard stats empty
2022/07/20 23:35:45 DbName  config/scan4all_db
2022/07/20 23:35:45 wait for init config files ... 
2022/07/20 23:35:46 init config files is over .
[INF] Running SYN scan with CAP_NET_RAW privileges
[INF] Port scan starting....
badger 2022/07/20 23:35:46 INFO: Got compaction priority: {level:0 score:1.73 dropPrefixes:[]}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x755b9d]

goroutine 1 [running]:
net/url.(*URL).Hostname(...)
	/opt/hostedtoolcache/go/1.18.4/x64/src/net/url/url.go:1133
github.com/hktalent/scan4all/lib.HoneyportDetection({0xc0003028f0, 0xe})
	/home/runner/work/scan4all/scan4all/lib/HoneypotDetection.go:27 +0xbd
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).mergeToFile(0xc00670e230)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:77 +0x565
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Load(0xc00670e230)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:30 +0x45
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc00670e230)
	/home/runner/work/scan4all/scan4all/pkg/naabu/v2/pkg/runner/runner.go:207 +0x245
main.main()
	/home/runner/work/scan4all/scan4all/main.go:68 +0x3b0

**Comment by hktalent** [comment]
@SkyBlueEternal thanks
```
$ ./scan4all -list test.txt -v -debug
badger 2022/07/21 15:09:22 INFO: All 1 tables opened in 2ms
badger 2022/07/21 15:09:22 INFO: Replaying file id: 0 at offset: 3692014
badger 2022/07/21 15:09:22 INFO: Replay took: 4.537µs
badger 2022/07/21 15:09:22 DEBUG: Value log discard stats empty
2022/07/21 15:09:22 DbName  config/scan4all_db
2022/07/21 15:09:22 wait for init config files ... 
2022/07/21 15:09:22 init config files is over .
Starting Nmap 7.92 ( https://nmap.org ) at 2022-07-21 15:09 CST
Read data files from: /usr/local/bin/../share/nmap
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.03 seconds

WARNING: No targets were specified, so 0 hosts scanned.

[INF] Running CONNECT scan with non root privileges
[INF] Port scan starting....
2022/07/21 15:09:22 /Users/51pwn/MyWork/scan4all/config/doNmapScan.sh /var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/stdin-input-105609745 /var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/stdin-out-2129365895
 Asynchronous go PoCs detection task %20.00 ....
```
Will be fixed in the next version tonight at 21:00

**Comment by hktalent** [comment]
@SkyBlueEternal 
remove local 
rm -rf ./config

and 

reTry
