### ISSUE TITLE
如何自定义NMAP扫描参数？

### ISSUE THREAD

**Issue by SkyBlueEternal** [hktalent/scan4all#40]
我在扫描时，只想扫描top 1000端口，并且支持ping检测。我修改json几次后没有效果。
我通过procExp观察到NMAP执行非预期指令。
```
nmap.exe  -F --top-ports=65535 -n --unique --resolve-all -Pn -sU -sS --min-hostgroup 64 --max-retries 0 --host-timeout 10m --script-timeout 3m --version-intensity 9 --min-rate 5000 -T4  -iL C:\Users\user\AppData\Local\Temp\stdin-input-1242664832 -oX C:\Users\user\AppData\Local\Temp\stdin-out-3822858477
```

**Comment by hktalent** [comment]
@SkyBlueEternal 修改
doNmapScanWin.bat
config.json

**Comment by hktalent** [comment]
在config.json中设置
"priorityNmap":true
<img width="533" alt="image" src="https://user-images.githubusercontent.com/18223385/181261177-76c5f1b4-0de9-436c-bcf3-92a21b837ed2.png">
然后修改：doNmapScanWin.bat
<img width="702" alt="image" src="https://user-images.githubusercontent.com/18223385/181261260-ff1da000-7a90-4e6b-8434-0e9830948a63.png">
