### ISSUE TITLE
Win下测试NMAP没有启动

### ISSUE THREAD

**Issue by SkyBlueEternal** [hktalent/scan4all#41]
我们使用procexp64.exe与procmon.exe观察scan4all调用nmap的行为；发现在scan4all加入300个C段同时扫描时，调用NMAP会出现异常。具体表现为程序卡死(卡死时间超过48小时)并且无报错，NMAP没有发起TCP SYN记录。

**Comment by hktalent** [comment]
nmap默认全端口300个C xxx.xxx.0.0/16 是很慢的，毕竟目标那么多
后期优化吧，直接使用你已经nmap好的xml结果

**Comment by hktalent** [comment]
@SkyBlueEternal 等等吧，还没有实现呢

**Comment by hktalent** [comment]
在config.json中设置
"priorityNmap":false

**Comment by hktalent** [comment]
@SkyBlueEternal 
download V2.6.6
