### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sajeeshab** [hktalent/scan4all#42]
go install github.com/hktalent/scan4all@2.6.1
# github.com/google/gopacket/pcap
go/pkg/mod/github.com/google/gopacket@v1.1.19/pcap/pcap_unix.go:34:10: fatal error: pcap.h: No such file or directory
   34 | #include <pcap.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by hktalent** [comment]
@Sajeeshab you can see:
https://github.com/hktalent/scan4all/blob/main/.github/workflows/build.yml

## macOS
```
brew install libpcap
```
## ubuntu
```
sudo apt install -yy libpcap-dev
```
