### ISSUE TITLE
nmap: unrecognized option '--unique'

### ISSUE THREAD

**Issue by sthakur23** [hktalent/scan4all#43]
nmap: unrecognized option '--unique'

[ERR] Could not run nmap command: exit status 255
[FTL] Could not run enumeration: Could not run nmap command: exit status 255

**Comment by hktalent** [comment]
$ nmap -v
Starting Nmap 7.92

check your map version

more using info ,you can see
https://github.com/hktalent/scan4all/blob/main/config/doNmapScan.sh
