### ISSUE TITLE
求解答·

### ISSUE THREAD

**Issue by ewfubwefwe** [hktalent/scan4all#44]
![image](https://user-images.githubusercontent.com/91933542/181883858-091c44c4-8041-4ed8-b5cf-70d11acec443.png)
win系统

**Comment by hktalent** [comment]
那个版本？

**Comment by ewfubwefwe** [comment]
2.6.8
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hktalent/scan4all"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月30日(星期六) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hktalent/scan4all] 求解答· (Issue #44)





 
那个版本？

**Comment by ewfubwefwe** [comment]
.\scan4all.exe -l .\1.txt -np -csv -o output.csv 

命令是这个下载下来直接用的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hktalent/scan4all"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月30日(星期六) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hktalent/scan4all] 求解答· (Issue #44)





 
那个版本？

**Comment by hktalent** [comment]
已经修复
下载使用
 2.6.9
版本
