### ISSUE TITLE
Release Mac OSX M1/M2 (arm64)  

### ISSUE THREAD

**Issue by secfb** [hktalent/scan4all#52]
The tool you wrote is really good. Can you share the mac osx(arm64) release version of this tool?

**Comment by hktalent** [comment]
https://github.com/hktalent/scan4all/releases
https://github.com/hktalent/scan4all/releases/download/2.6.8/scan4all_2.6.8_macOS_amd64.zip

**Comment by secfb** [comment]
I actually wanted a release for arm64.

**Comment by hktalent** [comment]
Download version 2.6.9 after 10 minutes

**Comment by hktalent** [comment]
https://github.com/hktalent/scan4all/releases/download/2.6.9/scan4all_2.6.9_macOS_arm64.zip
@secfb

**Comment by 9baller47** [comment]
> 

yes I can

**Comment by secfb** [comment]
I really thank you for your interest.
