### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by matmad** [hktalent/scan4all#53]
Hi
I constantly get this error when trying to compile on Windows:

cc1.exe: sorry, unimplemented: 64-bit mode not compiled in (exit status 2)

I have tried to install MinGW, but it did not help :(

Please advice

**Comment by hktalent** [comment]
you kan see
https://github.com/hktalent/scan4all/blob/main/.github/workflows/build.yml
https://github.com/hktalent/scan4all/blob/main/.github/build/windows.yml

In addition, our release is compiled and released through online automation, which is safe and reliable, and can be downloaded and used with confidence.
