### ISSUE TITLE
启动失败了

### ISSUE THREAD

**Issue by bingpo** [hktalent/scan4all#56]
![image](https://user-images.githubusercontent.com/5062793/182139017-99085463-849e-4af8-ab9d-dd87ce7ae076.png)
尝试了好几个版本都是这个错误，不清楚是哪里的问题

**Comment by bingpo** [comment]
![image](https://user-images.githubusercontent.com/5062793/182140209-e0e3c518-d8d5-455d-8b90-d58a3ce249c5.png)
==！好像还是一样的，刚下载的新的，问题依然存在

**Comment by hktalent** [comment]
win10 arm?

**Comment by bingpo** [comment]
> win10手臂？

win 11

**Comment by 9baller47** [comment]
hello I am confused .Explain to me better

**Comment by bingpo** [comment]
自己下载源码编译了一下，感觉又好了

**Comment by 9baller47** [comment]
Sounds good. How can i reach you? we can make money online together i know
alot in bank spamming do you have tutorials
