### ISSUE TITLE
运行过程中卡死的情况

### ISSUE THREAD

**Issue by bingpo** [hktalent/scan4all#60]
![image](https://user-images.githubusercontent.com/5062793/182264456-8aae0544-9fb4-44a3-9094-a544ce121b35.png)
扫描过程中出现“brady map[]} false” 这个会发生卡死的现象，程序到此处不会往下运行了

**Comment by hktalent** [comment]
后台在做密码爆破，
1、确认
"hydrathread": 64,
如果太小会很慢
太大会卡
