### ISSUE TITLE
Tool Usage Question

### ISSUE THREAD

**Issue by secfb** [hktalent/scan4all#64]
Hello,
I just want to crawl a website. I want the application to scan for vulnerabilities on the port I specified without doing a port scan. I just want it scanned for known vulnerabilities.
I created a command as follows. But the application still brute-forces the ssh port. How do I prevent it from brute-force?

```
scan4all -host http://scanme.nmap.org -p 80 -ep 22,3306 -stream -v
```

**Comment by hktalent** [comment]
priorityNmap=false ./scan4all -host http://scanme.nmap.org -p 80 -ep 22,3306 -stream -v
