### ISSUE TITLE
 fatal error

### ISSUE THREAD

**Issue by sherli297** [hktalent/scan4all#70]
![image](https://user-images.githubusercontent.com/85586714/182512949-342a614e-09f3-489e-be91-8be432d297de.png)
![image](https://user-images.githubusercontent.com/85586714/182513155-b82b83b1-9ef1-43fe-afcc-a63ddf4af32d.png)

I'm getting error while Installing go and git clone, here I'm attaching screenshots for your perusal, please take a look at them

**Comment by sherli297** [comment]
![image](https://user-images.githubusercontent.com/85586714/182515981-66a89b98-184e-4d7e-9e5b-728fb41fa2d2.png)

**Comment by hktalent** [comment]
1、update nmap to latest
or change config.json rm --unique
2、
docker ubuntu

apt update;apt install -yy libpcap0.8-dev
centos

yum install -yy glibc-devel.x86_64
