### ISSUE TITLE
Nmap unique causes freeze, then issue when re-scaning

### ISSUE THREAD

**Issue by math-ematics** [hktalent/scan4all#77]
Got the Nmap issue with --unique command, I have newest nmap installed. This causes script to stop.

Then abort and when rescanning

./scan4all -list ~/recon/httpx.txt -o scan4-test.txt
2022/08/03 08:02:37 wait for init config files ...
2022/08/03 08:02:37 Init2 k-v db cannot open multiple processes at the same time, or please delete the .DbCache directory and try again: Cannot acquire directory lock on ".DbCache".  Another process is using this Badger database.: resource temporarily unavailable
2022/08/03 08:02:37 init config files is over .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14a pc=0xa28214]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x2418da0?, 0xc00091fe48)
        /home/runner/work/scan4all/scan4all/vendor/github.com/dgraph-io/badger/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x21262c9?, {0x205fbaa?, 0x351dbc0?})
        /home/runner/work/scan4all/scan4all/lib/util/kvDb.go:75 +0x71
github.com/hktalent/scan4all/brute.init.2.func1()
        /home/runner/work/scan4all/scan4all/brute/fuzzAI.go:51 +0x16f
github.com/hktalent/scan4all/lib/util.DoInit(0x4?)
        /home/runner/work/scan4all/scan4all/lib/util/config.go:417 +0xb6
main.main()
        /home/runner/work/scan4all/scan4all/main.go:23 +0x5d

**Comment by math-ematics** [comment]
ls -la reveales .Dbcache dir but its not obvious to everyone.

**Comment by math-ematics** [comment]
Re-running gives nmap issues again.

./scan4all -list ~/recon/httpx.txt -o scan4-test.txt
2022/08/03 08:07:18 wait for init config files ...
2022/08/03 08:07:18 init config files is over .
2022/08/03 08:07:18 DbName  config/scan4all_db
2022/08/03 08:07:19 wait for all threads to end
Starting Nmap 7.80 ( https://nmap.org ) at 2022-08-03 08:07 CEST
Read data files from: /usr/bin/../share/nmap
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.92 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)

WARNING: No targets were specified, so 0 hosts scanned.

[INF] Running SYN scan with CAP_NET_RAW privileges
[INF] Port scan starting....
nmap: unrecognized option '--unique'
See the output of nmap -h for a summary of options.

**Comment by hktalent** [comment]
1、rm -rf .DbCache

2、change config.json
rm --unique
or update your mmap to new latest

**Comment by math-ematics** [comment]
Nmap is the latest I just told you that

**Comment by hktalent** [comment]
Mac OS
$ nmap -v
Starting Nmap 7.92
