### ISSUE TITLE
卡在Using Interactsh Server处

### ISSUE THREAD

**Issue by liuweimmm** [hktalent/scan4all#78]
![image](https://user-images.githubusercontent.com/90296627/182553404-b2b33203-9154-4dc4-b7f2-23446cd5573a.png)
操作系统版本：centos7.6
nmap版本：7.92
问题描述：
在执行./scan4all -host 192.168.1.158后，程序运行至截图出卡住，超过20分钟
192.168.1.158为存活的测试主机

**Comment by hktalent** [comment]
不要担心，他在后台给你干活呢，如果你想知道他在干什么
./scan4all -host 192.168.1.158 -v 
如果你还想知道细节
./scan4all -host 192.168.1.158 -v -debug
