### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by draksjahs** [hktalent/scan4all#79]
Hi,
I get error when I try to run the tool.
2022/08/03 21:54:09 wait for init config files ...
2022/08/03 21:54:13 Init2 k-v db 不能多个进程同时开启 Mmap value log file. Path=.DbCache/000000.vlog. Error=exec format error
2022/08/03 21:54:13 init config files is over .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14a pc=0xa27d54]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x24221c0?, 0xc000719e48)
        /home/draksjahs/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x2131586?, {0x206b128?, 0x35245d8?})
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220801134924-2de0a7bac927/lib/util/kvDb.go:75 +0x71
github.com/hktalent/scan4all/brute.init.2.func1()
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220801134924-2de0a7bac927/brute/fuzzAI.go:51 +0x16f
github.com/hktalent/scan4all/lib/util.DoInit(0x7?)
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220801134924-2de0a7bac927/lib/util/config.go:417 +0xb6
main.main()
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220801134924-2de0a7bac927/main.go:23 +0x5d

**Comment by hktalent** [comment]
download and use  release 2.7.1
rm -rf . DbCache
reTry

**Comment by draksjahs** [comment]
Hi @hktalent ,
still same error;

2022/08/04 20:24:43 wait for init config files ...
2022/08/04 20:24:46 Init2 k-v db cannot open multiple processes at the same time, or please delete the .DbCache directory and try again: Mmap value log file. Path=.DbCache/000000.vlog. Error=exec format error
2022/08/04 20:24:46 init config files is over .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14a pc=0xa41c54]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x52a?, 0xc000769e48)
        /home/draksjahs/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x21608a2?, {0x20997a6?, 0x3565ac0?})
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/lib/util/kvDb.go:75 +0x71
github.com/hktalent/scan4all/brute.init.2.func1()
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/brute/fuzzAI.go:51 +0x16f
github.com/hktalent/scan4all/lib/util.DoInit(0x7?)
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/lib/util/config.go:417 +0xb6
main.main()
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/main.go:23 +0x5d

**Comment by hktalent** [comment]
that version?

**Comment by umar98** [comment]
Still facing the same issue

**Comment by draksjahs** [comment]
Hi @hktalent ,
still not working. trying to use the latest version. same error;
command : scan4all


error;
2022/08/05 14:35:38 wait for init config files ...
2022/08/05 14:35:42 Init2 k-v db cannot open multiple processes at the same time, or please delete the .DbCache directory and try again: Mmap value log file. Path=.DbCache/000000.vlog. Error=exec format error
2022/08/05 14:35:42 init config files is over .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14a pc=0xa41c54]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x52a?, 0xc0063bbe48)
        /home/draksjahs/go/pkg/mod/github.com/dgraph-io/badger@v1.6.2/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x21608a2?, {0x20997a6?, 0x3565ac0?})
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/lib/util/kvDb.go:75 +0x71
github.com/hktalent/scan4all/brute.init.2.func1()
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/brute/fuzzAI.go:51 +0x16f
github.com/hktalent/scan4all/lib/util.DoInit(0x7?)
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/lib/util/config.go:417 +0xb6
main.main()
        /home/draksjahs/go/pkg/mod/github.com/hktalent/scan4all@v0.0.0-20220803035002-21c15d3054bb/main.go:23 +0x5d

**Comment by hktalent** [comment]
> that version? 1、mkdir db 2、download 2.7.2
> 
> reTry

rm -rf .DbCache/

reTry

**Comment by draksjahs** [comment]
Hi @hktalent ,
I already tried and got the same error again.

**Comment by hktalent** [comment]
windows?
what scan4all versions?
@draksjahs

**Comment by draksjahs** [comment]
Hi @hktalent ,
yes windows OS but I use kali linux wsl.

**Comment by hktalent** [comment]
@draksjahs 
I use kali,is ok

wget -c 'https://github.com/hktalent/scan4all/releases/download/2.7.4/scan4all_2.7.4_linux_amd64.zip'
unzip scan4all_2.7.4_linux_amd64.zip 
<img width="983" alt="image" src="https://user-images.githubusercontent.com/18223385/183256776-471f610c-3840-4602-95ca-8e98a0d7cb9f.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/18223385/183256799-ad2ed856-b389-4cfa-bb72-47351bd23e06.png">

**Comment by draksjahs** [comment]
Hi @hktalent ,
still got the same error again.
2022/08/07 21:11:58 wait for init config files ...
2022/08/07 21:11:59 Init2 k-v db cannot open multiple processes at the same time, or please delete the .DbCache directory and try again: Mmap value log file. Path=.DbCache/000000.vlog. Error=exec format error
2022/08/07 21:11:59 init config files is over .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14a pc=0xa28214]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x242cec0?, 0xc001151e48)
        /home/runner/work/scan4all/scan4all/vendor/github.com/dgraph-io/badger/txn.go:676 +0x34
github.com/hktalent/scan4all/lib/util.(*KvDbOp).Get(0x2133af1?, {0x206cd55?, 0x3537f20?})
        /home/runner/work/scan4all/scan4all/lib/util/kvDb.go:81 +0x71
github.com/hktalent/scan4all/brute.init.2.func1()
        /home/runner/work/scan4all/scan4all/brute/fuzzAI.go:51 +0x16f
github.com/hktalent/scan4all/lib/util.DoInit(0x7?)
        /home/runner/work/scan4all/scan4all/lib/util/config.go:428 +0xb6
main.main()
        /home/runner/work/scan4all/scan4all/main.go:23 +0x5d
