### ISSUE TITLE
扫描中断

### ISSUE THREAD

**Issue by klmyssn** [hktalent/scan4all#81]
[ERR] Could not run nmap command: exit status 255
[FTL] Could not run enumeration: Could not run nmap command: exit status 255

**Comment by hktalent** [comment]
1. Increase network bandwidth
2. Adjust the nmap parameters
change
XRate=5000
to
XRate=500

**Comment by klmyssn** [comment]
我没找到这个XRate参数哇，我在config.json里面发现配置的是“--min-rate 10000” 是修改这个吗？ 还是新增一个 --XRate=500 ？

**Comment by hktalent** [comment]
> * Increase network bandwidth
> * Adjust the nmap parameters
>   change doNmapScan.sh == --min-rate 10000
>   XRate=5000
>   to
>   XRate=500

and change config.json
--min-rate 10000
to
--min-rate 500

**Comment by klmyssn** [comment]
好的，感谢
