### ISSUE TITLE
Off-by-one error detected

### ISSUE THREAD

**Issue by raheel0x01** [hktalent/scan4all#82]
`pocs_go/ms/DCom.go`

Index() can return -1; maybe you wanted to do recvStr_v2[:packet_v2_end+1] ![Image](https://user-images.githubusercontent.com/65211256/183235976-09b851eb-68ea-48e2-9ca2-71ef97c53ccd.png)

An off-by-one error occurs as a result of incorrectly handled edge-cases. It is recommended that the program be thoroughly tested for one-off bugs.

**Comment by hktalent** [comment]
@raheel0x01 thanks
