### ISSUE TITLE
Stumbled: Nmap done: 0 IP addresses (0 hosts up)

### ISSUE THREAD

**Issue by aels** [hktalent/scan4all#83]
```
[root@ded87601 bin]# /root/go/bin/scan4all -host 144.92.1.1/24
2022/08/07 10:06:11 wait for init config files ...
2022/08/07 10:06:12 init config files is over .
2022/08/07 10:06:12 DbName  config/scan4all_db
2022/08/07 10:06:12 wait for all threads to end
Starting Nmap 7.92 ( https://nmap.org ) at 2022-08-07 10:06 AEST
Read data files from: /usr/bin/../share/nmap
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.07 seconds
           Raw packets sent: 0 (0B) | Rcvd: 0 (0B)

WARNING: No targets were specified, so 0 hosts scanned.

[INF] Running SYN scan with CAP_NET_RAW privileges
[INF] Port scan starting....
```
why nmap won't catch hosts?

**Comment by hktalent** [comment]
$ priorityNmap=true ./scan4all -host 192.168.10.1/24 -v
2022/08/08 09:48:43 wait for init config files ... 
2022/08/08 09:48:43 init config files is over .
2022/08/08 09:48:43 DbName  config/scan4all_db
2022/08/08 09:48:43 wait for all threads to end
Starting Nmap 7.92 ( https://nmap.org ) at 2022-08-08 09:48 CST
Read data files from: /usr/local/bin/../share/nmap
Nmap done: 0 IP addresses (0 hosts up) scanned in 0.03 seconds

WARNING: No targets were specified, so 0 hosts scanned.

[INF] Running CONNECT scan with non root privileges
[INF] Port scan starting....
2022/08/08 09:48:43 /Users/51pwn/MyWork/scan4all/config/doNmapScan.sh /var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/stdin-input-2661041743 /var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/stdin-out-1154407985


cat /var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/stdin-input-2661041743
192.168.10.1/24


It doesn't seem to be a problem, and the following information is used to determine whether nmap really exists
“Nmap done: 0 IP addresses (0 hosts up) scanned in 0.03 seconds”
