### ISSUE TITLE
Could not run enumeration: Could not run nmap command: exit status 255

### ISSUE THREAD

**Issue by mohnqwerty** [hktalent/scan4all#84]
While running the scanner got this error i'm running on Ubuntu 18.04 wsl 

Running nmap command: nmap -n --unique --resolve-all -Pn --min-hostgroup 64 --max-retries 0 --host-timeout 10m --script-timeout 3m -oX /tmp/scan4all-out528460591 --version-intensity 9 --min-rate 10000 -T4 -p 80,443 192.168.2.2
[ERR] Could not run nmap command: exit status 255
[FTL] Could not run enumeration: Could not run nmap command: exit status 255

**Comment by hktalent** [comment]
1、you can run nmap first
2、run
./scan4all -l xxxNmapResult.xml -v
