### ISSUE TITLE
`pkg/ksubdomain/ksbdomain.go:39:8: no new variables on left side of :=`

### ISSUE THREAD

**Issue by kvtb** [hktalent/scan4all#87]
Build failed with `pkg/ksubdomain/ksbdomain.go:39:8: no new variables on left side of :=`

https://github.com/hktalent/scan4all/blob/89f08dd5b616e369011e5500583dc6d70c65f26a/pkg/ksubdomain/ksbdomain.go#L39

**Comment by hktalent** [comment]
thanks
