### ISSUE TITLE
Error using the latest version on Mac

### ISSUE THREAD

**Issue by Teicu** [hktalent/scan4all#88]
Hi, 

why I get this error and how to fix it? thanks
 

[INF] Using Nuclei Engine 2.7.5 (latest)
[INF] Using Nuclei Templates 9.1.5 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 2252
[INF] Templates clustered: 122 (Reduced 1470 HTTP Requests)
[INF] Using Interactsh Server: oast.site
fatal error: concurrent map writes

> goroutine 14688 [running]:
> runtime.throw({0x5d1a0f2?, 0x40f1905?})
> 	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc01391b290 sp=0xc01391b260 pc=0x4037f11
> runtime.mapassign_faststr(0x5cc1743?, 0x5?, {0xc0123457b0, 0xa})
> 	/usr/local/go/src/runtime/map_faststr.go:212 +0x39c fp=0xc01391b2f8 sp=0xc01391b290 pc=0x40161fc
> github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeRequest(0xc00c721520, {0xc00a72cf40, 0x19}, 0xc012ebb180, 0xc00bd711a0?, 0x0, 0xc00bd711d0, 0x0?)
> 	/Users/test/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.5/pkg/protocols/http/request.go:596 +0x2b4f fp=0xc01391bf38 sp=0xc01391b2f8 pc=0x52dc0ef
> github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP.func1(0x8bd3180?)
> 	/Users/test/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.5/pkg/protocols/http/request.go:211 +0x9f fp=0xc01391bfc8 sp=0xc01391bf38 pc=0x52d7e9f
> github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP.func2()
> 	/Users/test/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.5/pkg/protocols/http/request.go:217 +0x2a fp=0xc01391bfe0 sp=0xc01391bfc8 pc=0x52d7dca
> runtime.goexit()
> 	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc01391bfe8 sp=0xc01391bfe0 pc=0x406ad21
> created by github.com/projectdiscovery/nuclei/v2/pkg/protocols/http.(*Request).executeTurboHTTP
> 	/Users/test/go/pkg/mod/github.com/projectdiscovery/nuclei/v2@v2.7.5/pkg/protocols/http/request.go:208 +0x37f
> 
> goroutine 1 [semacquire]:
> sync.runtime_Semacquire(0xc000b916a0?)
> 	/usr/local/go/src/runtime/sema.go:56 +0x25
> sync.(*WaitGroup).Wait(0x5d3f785?)
> 	/usr/local/go/src/sync/waitgroup.go:136 +0x52
> main.main()
> 	/Users/test/scan4all/main.go:36 +0x131
> 
> goroutine 19 [chan receive]:
> github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
> 	/Users/test/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:882 +0x6a
> created by github.com/golang/glog.init.0
> 	/Users/test/go/pkg/mod/github.com/golang/glog@v1.0.0/glog.go:410 +0x1bf

**Comment by hktalent** [comment]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/18223385/185087141-2c16fed8-5f90-4019-8e9f-371fdf079685.png">
Don't update vendor at will, the internal code is optimized and bugs fixed by us

It is recommended that you download and use directly from the release
https://github.com/hktalent/scan4all/releases

**Comment by Teicu** [comment]
I did exactly that and after it starts scanning, I get this error 

<img width="742" alt="Screenshot 2022-08-17 at 12 49 32" src="https://user-images.githubusercontent.com/1572822/185089487-bfeb62bc-2455-462f-90a9-d84e39714991.png">

**Comment by hktalent** [comment]
It is recommended that the CPU should not be less than 2 cores and the memory should not be less than 8G.

**Comment by Teicu** [comment]
<img width="257" alt="Screenshot 2022-08-17 at 13 13 01" src="https://user-images.githubusercontent.com/1572822/185094157-b480cf6a-2cbe-46a7-b00b-91d35e803de6.png">
 
this is my config mate

**Comment by hktalent** [comment]
cat lists.txt|xargs -I % ./scan4all -host %

**Comment by hktalent** [comment]
https://github.com/golang/go/issues/24484
Can you provide more information?
