### ISSUE TITLE
Error start in windows 

### ISSUE THREAD

**Issue by MissisEliot** [hktalent/scan4all#9]
C:UsersAdministratorDesktopscan4all_2.2.5_windows_amd64
> scan4all.exe -host http://www.cnu.cc/
badger 2022/06/22 12:19:37 INFO: All 0 tables opened in 0s
badger 2022/06/22 12:19:37 INFO: Replaying file id: 0 at offset: 0
2022/06/22 12:19:37 Init k-v db 不能多个进程同时开启 Value log truncate required to run DB. This might result in data loss
2022/06/22 12:19:37 config.ReadInConfig open config/config.json: The system cannot find the path specified.
[INF] Running CONNECT scan with non root privileges
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x14a pc=0xb329d4]

goroutine 1 [running]:
github.com/dgraph-io/badger.(*DB).View(0x12?, 0xc005b75708)
D:/a/scan4all/scan4all/vendor/github.com/dgraph-io/badger/txn.go:676 +0x34
github.com/hktalent/scan4all/pkg.(*KvDbOp).Get(0xc00576a10f?, {0xc00576a10f?, 0x24ba6e4?})
D:/a/scan4all/scan4all/pkg/kvDb.go:59 +0x71
github.com/hktalent/scan4all/pkg.DoDns({0xc00576a108, 0x12})
D:/a/scan4all/scan4all/pkg/domain.go:77 +0x1c5
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).PreProcessTargets.func1(0xc0058be760?, 0xc0058e6000?, {0xc00576a108, 0x12})
D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:101 +0x95
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).PreProcessTargets(0xc00609a460)
D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:113 +0x234
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Load(0xc00609a460)
D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/targets.go:34 +0x7a
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).RunEnumeration(0xc00609a460)
D:/a/scan4all/scan4all/pkg/naabu/v2/pkg/runner/runner.go:194 +0x245
main.main()
D:/a/scan4all/scan4all/main.go:20 +0x187

**Comment by MissisEliot** [comment]
Help me plz)

**Comment by hktalent** [comment]
rm curl dir
.DbCache
retry
