### ISSUE TITLE
Unable to update, update error reported.

### ISSUE THREAD

**Issue by Trapshell** [hktalent/scan4all#92]
`./scan4all -version`
[INF] Current Version: 2.0.7

` ./scan4all -update` 
[FTL] Program exiting: no input list provided

<img width="580" alt="Snipaste_2022-08-18_09-46-20" src="https://user-images.githubusercontent.com/106905547/185274055-f13ada97-1318-426f-861f-4d8e2d59e896.png">

I found that scan4ll is updated, and I reported an error when I tried to update
I using the Compilation installation method :see_no_evil:

```sh
git clone https://github.com/hktalent/scan4all.git
cd scan4all
go build
```

**Comment by hktalent** [comment]
$ ./scan4all -update
2022/08/18 09:57:16 wait for init config files ... 
2022/08/18 09:57:16 init config files is over .
2022/08/18 09:57:16 DbName  config/scan4all_db
2022/08/18 09:57:16 wait for all threads to end
[INF] Running CONNECT scan with non root privileges
2022/08/18 09:57:18 debug fetch "https://github.com/hktalent/scan4all/releases/download/2.7.5/scan4all_2.7.5_macOS_amd64.zip"
2022/08/18 09:57:20 debug response 200 OK – application/octet-stream (23718 KiB)
2022/08/18 09:57:20 debug copy to "/var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/update-148219058"
[================================================] 100%
2022/08/18 09:57:23 debug copied                   
2022/08/18 09:57:23 debug unpacking "/var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/update-148219058"
2022/08/18 09:57:24 debug copy "/var/folders/_l/pnb2t_9s0f192bqlz1348vpr0000gn/T/unpackit-3311748681/scan4all" to "/Users/51pwn/go/bin/scan4all.tmp"
2022/08/18 09:57:24 debug renaming "/Users/51pwn/go/bin/scan4all.tmp" to "/Users/51pwn/go/bin/scan4all"
[INF] Successfully updated to scan4all_2.7.5_macOS_amd64.zip
2022/08/18 09:57:24 start clear noRpt cahe
