### ISSUE TITLE
invalid char '–'

### ISSUE THREAD

**Issue by spidyhackx** [hktalent/scan4all#93]
hi, i tried to install the package but i am getting this error

![image](https://user-images.githubusercontent.com/40536205/185429315-0dc3ba55-4af4-44ab-b52a-31056711eeb0.png)

**Comment by hktalent** [comment]
thanks
$ go install github.com/hktalent/scan4all@2.7.6
go: downloading github.com/hktalent/scan4all v0.0.0-20220818160506-e42bfd501cc1
51pwn@123 Web-Scan $ 

now is ok
