### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by spidyhackx** [hktalent/scan4all#94]
after all the packages are downloaded, this error throws up.
```go version: 1.19 amd64 linux```

![image](https://user-images.githubusercontent.com/40536205/185487731-d364774d-0a5b-4565-af44-f33a83cac185.png)

**Comment by hktalent** [comment]
download and use release
thanks

or
more see:
https://github.com/hktalent/scan4all/blob/main/.github/workflows/build.yml
Mac OS:
brew install libpcap

linux:
sudo apt install -yy libpcap-dev
